funciones_cripto.cc File Reference
#include <iostream>
#include <string>
#include <cstring>
#include `funciones_cripto.h`
Functions
void Usage (int argc, char *argv[])
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
string XOR (string texto)
string CesarEncriptar (string texto, int clave)
string CesarDesencriptar (string texto, int clave)
Function Documentation
CesarDesencriptar()
string CesarDesencriptar (string texto, int clave)
Definition at line 70 of file funciones_cripto.cc.
Referenced by main().
                                                 {
  string resultado = "";
  for(int i = 0; i <texto.length(); i++){
    if(isalpha(texto[i])){
      if(isupper(texto[i])){
      resultado = resultado + char((int(texto[i]- clave - 'A') % 26) + 'A');
    } else {
      resultado = resultado + char((int(texto[i]- clave - 'a') % 26) + 'a');
      }
    }
  }
  return resultado;
}
CesarEncriptar()
string CesarEncriptar (string texto, int clave)
Definition at line 56 of file funciones_cripto.cc.
Referenced by main().
                                              {
  string resultado = "";
  for(int i = 0; i <texto.length(); i++){
      if(isalpha(texto[i])){
        if(isupper(texto[i])){
          resultado = resultado + char((int(texto[i]+ clave - 'A') % 26) + 'A');
        } else {
          resultado = resultado + char((int(texto[i]+ clave - 'a') % 26) + 'a');
            }
      }
  }
  return resultado;
}
Usage()
void Usage (int argc, char * argv[])
Universidad de La Laguna Escuela Superior de Ingeniería y Tecnología Grado en Ingeniería Informática Informática Básica.
Author
F. de Sande
Date
7.nov.2020 Cada nuevo término de la serie de Fibonacci se genera sumando los dos anteriores. Comenzando con 0 y 1, los primeros 10 términos serán: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34 Desarrolle en C++ un programa que calcule la suma de todos los términos de valor par de la serie que sean menores que 1000.
See also
https://docs.google.com/document/d/1-3hTIVf8tPrbn9u0vs0Cm2IGyX1XBgv8hReVU0KOSUQ/edit?usp=sharing
stoi http://www.cplusplus.com/reference/string/stoi/ An Object Oriented Version of the program:
https://stackoverflow.com/questions/21360694/sum-of-even-fibonacci-numbers-under-1000Muestra el modo de uso correcto del programa En caso de que el uso no sea el correcto, muestra el mensaje y finaliza la ejecución del programa. El programa precisa un único número natural para su ejecución.
Parameters
in argc Number of command line parameters
in argv Vector containing (char*) the parameters
Definition at line 23 of file funciones_cripto.cc.
References kHelpText.
                                  {
  if(argc <= 1){
    cout << argv[0] << " -- Cifrado de ficheros" << endl;
    cout << "Modo de uso: " << argv[0] << " fichero_entrada fichero_salida método password operación" <<
      endl;
    cout << "Pruebe " << argv[0] << " --help para más información" << endl;
    exit(EXIT_SUCCESS);
  }
  string parametro{argv[1]};
  if(parametro == "--help"){
    cout << argv[0] << " -- Cifrado de ficheros" << endl;
    cout << "Modo de uso: " << argv[0] << " fichero_entrada fichero_salida método password operación" <<
      endl << endl;
    cout << "fichero_entrada: Fichero a codificar" << endl;
    cout << "fichero_salida: Fichero codificaco" << endl;
    cout << "método: Indica el método de encriptado" << endl;
    cout << " 1: Cifrado XOR" << endl;
    cout << " 2: Cifrado César" << endl;
    cout << "password: Letra (mayúscula) secreta en el caso del método 1, Valor de K en el método 2"
       << endl;
    cout << "operación: Operación a realizar en el fichero" << endl;
    cout << " +: encriptar el fichero" << endl;
    cout << " -: desencariptar el fichero" << endl;
    exit(EXIT_SUCCESS);
  }
}
XOR()
string XOR (string texto)
Definition at line 47 of file funciones_cripto.cc.
Referenced by main().
                         {
    char clave = 'F'; //Solo funciona con letras mayúsculas y no usa la clave introducida
       por línea de comandos.
    string salida = texto;
    
    for (int i = 0; i < salida.size(); i++)
        salida[i] = salida[i] ^ clave;
    return salida;
}